# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=b'Timestamp')),
                ('count', jsonfield.fields.JSONField(default=dict)),
                ('volume', jsonfield.fields.JSONField(default=dict)),
                ('price', jsonfield.fields.JSONField(default=dict)),
                ('litre_price', jsonfield.fields.JSONField(default=dict)),
                ('alcohol_price', jsonfield.fields.JSONField(default=dict)),
                ('vintage', jsonfield.fields.JSONField(default=dict)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name=b'Category')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Country', verbose_name=b'Country')),
            ],
            options={
                'ordering': ('timestamp', 'country'),
            },
        ),
    ]
