# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 17:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Store name')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Store address')),
                ('zip_code', models.CharField(db_index=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='Zip code')),
                ('postal', models.CharField(db_index=True, max_length=255, verbose_name='Postal')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=9, verbose_name='GPS latitude')),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10, verbose_name='GPS longitude')),
                ('opening_times', jsonfield.fields.JSONField(default=dict)),
                ('opening_times_next', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.IntegerField(db_index=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Category number')),
            ],
            options={
                'ordering': ('category_number',),
            },
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.StoreCategory'),
        ),
    ]
