version: '3.7'

services:
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend/src:/app/src
  backend:
    build:
      target: dev
    environment:
      DEBUG: "True"
      HTTP_HOST: localhost
      HTTP_PORT: "${HTTP_PORT:-8080}"
      SECRET_KEY: super_secret_key
      VINMONOPOLET_API_KEY: "${VINMONOPOLET_API_KEY}"
      DB_HOST: db
      DB_NAME: finmonopolet
      DB_USER: finmonopolet
      DB_PASSWORD: password
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME:-finmonopolet}"
      POSTGRES_USER: "${DB_USER:-finmonopolet}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
