version: '3.7'

services:
  frontend:
    build: frontend
    environment:
      - DEBUG
    ports:
      - "${HTTP_PORT:-8080}:8080"
    depends_on:
     - backend
  backend:
    build: backend
    ports:
      - "${HTTP_PORT_BACKEND:-8081}:8081"
