version: '3.7'

services:
  frontend:
    build:
      target: dev
      args:
        API_HOST: "${HTTP_SCHEME:-http}://${HTTP_HOST}:${HTTP_PORT_BACKEND:-8081}"
    volumes:
      - ./frontend/src:/app/src
  backend:
    build:
      target: dev
    environment:
      DEBUG: "True"
      HTTP_HOST: localhost
      HTTP_PORT: "${HTTP_PORT:-8080}"
      SECRET_KEY: super_secret_key
      DB_HOST: database
      DB_NAME: finmonopolet
      DB_USER: finmonopolet
      DB_PASSWORD: password
    volumes:
      - ./backend/src:/app/src
  database:
    environment:
      POSTGRES_DB: finmonopolet
      POSTGRES_USER: finmonopolet
      POSTGRES_PASSWORD: password
