# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.IntegerField(db_index=True, unique=True, verbose_name='Product ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Product name')),
                ('url', models.URLField(verbose_name='Product URL')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('volume', models.DecimalField(db_index=True, decimal_places=2, max_digits=5, verbose_name='Volume')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='Price')),
                ('litre_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='Price per litre')),
                ('alcohol_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price per unit of alcohol')),
                ('fullness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Fullness')),
                ('freshness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Freshness')),
                ('tannins', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Tannins')),
                ('bitterness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Bitterness')),
                ('sweetness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Sweetness')),
                ('color', models.TextField(blank=True, null=True, verbose_name='Color description')),
                ('smell', models.TextField(blank=True, null=True, verbose_name='Smell description')),
                ('taste', models.TextField(blank=True, null=True, verbose_name='Taste description')),
                ('country', models.CharField(db_index=True, max_length=255, verbose_name='Country of origin')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District of origin')),
                ('sub_district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub district of origin')),
                ('vintage', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Vintage')),
                ('feedstock', models.TextField(blank=True, null=True, verbose_name='Ingredients')),
                ('production_method', models.TextField(blank=True, null=True, verbose_name='Production method')),
                ('alcohol', models.DecimalField(db_index=True, decimal_places=2, max_digits=4, verbose_name='Alcohol percentage')),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grams of sugar per litre')),
                ('acid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grams of acid per litre')),
                ('storage', models.TextField(blank=True, null=True, verbose_name='How to store product')),
                ('producer', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Producer')),
                ('wholesaler', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wholesaler')),
                ('distributor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Distributor')),
                ('packaging', models.CharField(max_length=255, verbose_name='Packaging type')),
                ('cork', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cork type')),
                ('suits', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suits')),
                ('active', models.BooleanField(default=True, verbose_name='Tilgjengelig')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.Category')),
            ],
            options={
                'ordering': ('name', 'volume'),
            },
        ),
    ]
