# Generated by Django 3.0.5 on 2020-04-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sort_name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sort_name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sort_name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sort_name', models.CharField(db_index=True, max_length=255)),
                ('product_number', models.IntegerField(db_index=True, unique=True)),
                ('alcohol_content', models.DecimalField(db_index=True, decimal_places=2, max_digits=4)),
                ('volume', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('litre_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('alcohol_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('vintage', models.IntegerField(db_index=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Country')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Producer')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductType')),
            ],
            options={
                'ordering': ['sort_name', 'volume'],
            },
        ),
    ]
