# Generated by Django 3.0.5 on 2020-04-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
