# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Category name')),
                ('canonical_name', models.CharField(db_index=True, max_length=255, verbose_name='Canonical category name')),
            ],
            options={
                'ordering': ('canonical_name',),
            },
        ),
    ]
