# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('canonical_name', models.CharField(db_index=True, max_length=255, verbose_name='Canonical name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, verbose_name='Slug')),
            ],
            options={
                'ordering': ('canonical_name',),
                'abstract': False,
            },
        ),
    ]
